<?php
//$message="503 service unavailable";
//$sendBack=true;
//return;
if(!$isMe){
	die();
}
$years = date('Y-m');
//（粗暴地）获取参数
$img = "C:/BotQQ/php/src/holdsign/".$argv[0].".jpg";
if(!file_exists($img)){
	$message="Image file not found.";
	$sendBack=true;
	return;
}
$text = $argv[1];
//检查text参数
if ($text == "") {$text = "请增加text参数！";}
if(!badWords($text)){
    $message="请不要说不好的东西哦~";
	$sendBack=true;
	return;
}
if(strlen($text)>=16){
	$message="文字长度超过上限！（8个字）";
	$sendBack=true;
	return;
}

//新建图象
//$pic=imagecreate(500,40);
$pic = imagecreatefromjpeg($img);
//定义黑白颜色
$black = imagecolorallocate($pic, 0, 0, 0);
$gray = imagecolorallocate($pic, 80, 80, 80);
$white = imagecolorallocate($pic, 255, 255, 255);
//如果真 percent不等于空

//取图像大小
    list($width, $height) = getimagesize($img);

//定义字体
$font = "c://WINDOWS//fonts//simhei.ttf";
//定义输出字体串
$str = $text;
$declam="Generated by HeXiaoling!bot
requested by QQ: ".$sender;
//写文字
imagettftext($pic, 30, 9, 220, 140, $black, $font, $str);
imagettftext($pic, 10, 0, 10, $height-25, $gray, $font, $declam);
//生成GIF
$imgName=randStr();
$url = "C:/BotQQ/php/site/static/".$years."/".$imgName.".jpg";  
        $dir_name=dirname($url);
          //目录不存在就创建
          if(!file_exists($dir_name))
          {
            //iconv防止中文名乱码
           $res = mkdir(iconv("UTF-8", "GBK", $dir_name),0777,true);
          }
imagejpeg($pic,$url);
//销毁图像
imagedestroy($pic);
//send back image
$message="转换完成！请在这里查看和保存~
https://qq.acgn.pro/checkout.php?type=jpg&fpass=".$imgName;
$sendBack=true;