<?php
# This file was automatically generated by the YeziiBot installer.
# 此文件由YeZiiBot安装器自动生成
# If you make manual changes, please keep track in case you need to recreate them later.
# 如果你进行修改，请关注您的修改以备日后您需要再做重新修改
#
# Enjoy your time with YeZiiBot~
# 与YeZiiBot玩得开心~
#

## YeziiBot's name. e.g. 何小绫
$wgBotName = "";

## YeziiBot's server ID
$wgServerID = "undefined";

## Manager's QQ ID goes here
$wgUserID = "";

## The URL base path to the directory containing the YeziiBot;
## defaults for all runtime URL paths are based off of this.
$wgScriptPath = "";

#custom settings
##Maximum number that can be roll out.
$wgMaxRoll = 3000;

##Maxiumu lenght that a ticket can be create.
$wgMaxTicketLength = 200;